/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductDTO = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'buyLink' : IDL.Text,
  'category' : IDL.Text,
  'previewAudioUrl' : IDL.Text,
  'price' : IDL.Text,
});
export const Service = IDL.Variant({
  'fullProject' : IDL.Null,
  'videoEditing' : IDL.Null,
  'musicProduction' : IDL.Null,
  'videoDirection' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'service' : Service,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const InquiryDTO = IDL.Record({
  'service' : Service,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([ProductDTO], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], []),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
  'submitInquiry' : IDL.Func([InquiryDTO], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductDTO = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'buyLink' : IDL.Text,
    'category' : IDL.Text,
    'previewAudioUrl' : IDL.Text,
    'price' : IDL.Text,
  });
  const Service = IDL.Variant({
    'fullProject' : IDL.Null,
    'videoEditing' : IDL.Null,
    'musicProduction' : IDL.Null,
    'videoDirection' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'service' : Service,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const InquiryDTO = IDL.Record({
    'service' : Service,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([ProductDTO], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], []),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
    'submitInquiry' : IDL.Func([InquiryDTO], [], []),
  });
};

export const init = ({ IDL }) => { return []; };